import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import { QueryClientProviderComponent } from '@/providers/QueryClientProviderComponent';
import { ThemeProvider } from '@/components/providers/theme-provider';

const geistSans = GeistSans;

const geistMono = GeistMono;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientProviderComponent>
            {children}
          </QueryClientProviderComponent>
        </ThemeProvider>
      </body>
    </html>
  );
}
