name: Rust CI

on:
  push:
    branches: [ "main" ]
    paths: # Trigger only when backend code or the workflow itself changes
      - '.github/workflows/ci.yml'
      - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths: # Trigger only when backend code or the workflow itself changes
      - '.github/workflows/ci.yml'
      - 'backend/**'

env:
  CARGO_TERM_COLOR: always
  # Define cache key prefix for easier invalidation if needed
  CACHE_PREFIX: v1

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache cargo registry and index
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-registry-${{ env.CACHE_PREFIX }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-${{ env.CACHE_PREFIX }}-

      # Separate cache step for sqlx-cli binary
      - name: Cache sqlx-cli binary
        id: cache-sqlx-cli
        uses: actions/cache@v4
        with:
          path: ./target/ci-tools/bin/sqlx # Correct binary name is 'sqlx'
          key: ${{ runner.os }}-sqlx-cli-0.7.4-${{ env.CACHE_PREFIX }}
          restore-keys: |
            ${{ runner.os }}-sqlx-cli-0.7.4-${{ env.CACHE_PREFIX }}

      - name: Cache cargo build target directory
        uses: actions/cache@v4
        with:
          # Cache target directory relative to backend
          path: backend/target
          key: ${{ runner.os }}-cargo-build-${{ env.CACHE_PREFIX }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-${{ env.CACHE_PREFIX }}-

      # Install sqlx-cli only if the cache didn't hit
      - name: Install sqlx-cli
        if: steps.cache-sqlx-cli.outputs.cache-hit != 'true'
        run: |
          cargo install sqlx-cli \
            --version=0.7.4 \
            --features native-tls,postgres \
            --no-default-features \
            --root ./target/ci-tools
            # --locked # Remove --locked flag

      # Add the installation directory to PATH
      - name: Add sqlx-cli dir to PATH
        run: echo "$GITHUB_WORKSPACE/target/ci-tools/bin" >> $GITHUB_PATH

      - name: Check formatting
        run: cargo fmt --check
        working-directory: ./backend

      - name: Run Clippy
        run: cargo clippy -- -D warnings
        working-directory: ./backend

      - name: Check SQLx query cache # Reverted to original check step
        run: cargo sqlx prepare --check --workspace
        working-directory: ./backend

      - name: Run tests
        # Build steps will leverage cached target directory if possible
        run: cargo test
        working-directory: ./backend 