name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      # TODO: sqlx-cliが必要になったらコメント解除する
      # - name: Install sqlx-cli
      #   run: \
      #     cargo install sqlx-cli \
      #       --version=0.7.3 \
      #       --features rustls,postgres \
      #       --no-default-features \
      #       --locked

      - name: Check formatting
        run: cargo fmt --check
        working-directory: ./backend

      - name: Run Clippy
        run: cargo clippy -- -D warnings
        working-directory: ./backend

      - name: Run tests
        run: cargo test
        working-directory: ./backend 